title: "Rutherford Craze"
email: rutherford@craze.co.uk
description: >-
  The personal website of Rutherford Craze, a Netherlands-based
  typeface designer & font engineer from the UK.
baseurl: ""
url: "https://craze.co.uk"
github_username: rutherfordcraze

timezone: "Europe/Amsterdam"
encoding: "utf-8"

permalink: /:categories/:title:output_ext

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "articles"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"