title: "Rutherford Craze"
email: rutherford@craze.co.uk
description: >-
  The personal website of Rutherford Craze, a Netherlands-based
  typeface designer & font engineer from the UK.
baseurl: ""
url: "https://craze.co.uk"
github_username: rutherfordcraze

timezone: "Europe/Amsterdam"
encoding: "utf-8"

kramdown:
  auto_ids: false

collections_dir: collections
collections:
  work:
    output: true
    permalink: /work/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /articles/:slug